pipeline {
    agent any
    stages {
        stage('Testing Maven') {
                    steps {
                        sh """mvn -version"""
                    }
        }
        stage('Checkout') {
          steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], userRemoteConfigs: [[url: 'https://github.com/votre-utilisateur/votre-repo.git']]])
          }
        }
        stage('Afficher la date système') {
              steps {
                sh 'date'
              }
        }
    }
}
