pipeline {
    agent any
    stages {
        stage('Testing Maven') {
                    steps {
                        sh """mvn -version"""
                    }
        }
        stage('Afficher la date système') {
              steps {
                sh 'date'
              }
        }
        stage('GIT') {
                    steps {
                        echo "getting project from git"
                        withCredentials([usernamePassword(credentialsId: 'b746e1b5-725b-4f40-8058-804123acf9aa', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                            git branch: 'main', credentialsId: 'b746e1b5-725b-4f40-8058-804123acf9aa', url: 'https://github.com/Oumayma-Bah/tp_esprit.git'
                        }
                    }
        }
        stage('MVN CLEAN') {
                    steps {
                    dir('avec-maven'){
                        sh 'mvn clean'
                        }
                    }
        }
        stage('MVN COMPILE') {
                    steps {
                    dir('avec-maven'){
                        sh 'mvn compile'
                        }
                    }
        }
        stage('MVN SONARQUBE') {
            environment {
                SONAR_LOGIN = credentials('4b2d9ca2-2d87-41be-b9ec-7681caea0426')
            }
            steps {
                script {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn sonar:sonar -Dsonar.login=${env.SONAR_LOGIN}"
                    }
                }
            }
                
        }

    }
}
